### ISSUE TITLE
Unable to navigate to rendered documentation for Copy Offload API

### ISSUE THREAD

**Issue by mcfadden8** [NearNodeFlash/NearNodeFlash.github.io#111]
When I select the [CreateRequest API ](https://github.com/NearNodeFlash/nnf-dm/blob/master/daemons/compute/Readme.md#create-request) link from the last paragraph of the fully rendered [Data Movement ](https://nearnodeflash.github.io/v0.0.6/guides/data-movement/readme/#copy-offload-api-daemon) documentation, I am taken to the readme markdown document for the  nnf-dm deamons.  The [API Definition ](https://github.com/NearNodeFlash/nnf-dm/blob/master/daemons/compute/Readme.md#api-definition) section within this readme file offers a link to the [Copy Offload API Documentation](https://github.com/NearNodeFlash/nnf-dm/blob/master/daemons/compute/copy-offload-api.html) which takes me to the html source code for the offload API.

My expected behavior is to have a link to the rendered documentation so that I may read it.

**Comment by bdevcich** [comment]
@mcfadden8, this has been fixed and the API docs have been added to the development version of our documentation: https://nearnodeflash.github.io/dev/guides/data-movement/copy-offload-api.html

Links have been added for the Copy Offload API and the link in the last paragraph of the Data Movement Documenation has been fixed to point to it.

**Comment by mcfadden8** [comment]
Unfortunately, this problem is still happening to me.

**Comment by bdevcich** [comment]
You will need to make sure you are viewing the `dev` version of the documenation: https://nearnodeflash.github.io/dev/

You can get to this from the dropdown on the top of the page: 
![Screenshot 2023-10-31 at 3 02 37 PM](https://github.com/NearNodeFlash/NearNodeFlash.github.io/assets/89158881/42a6d974-fd9c-43e9-9e40-6fbf2803b2c5)

You can then navigate to the Copy Offload API docs directly (or use the link in that last paragraph): 
![Screenshot 2023-10-31 at 3 04 37 PM](https://github.com/NearNodeFlash/NearNodeFlash.github.io/assets/89158881/6de14850-a91e-47c9-97b2-dd176c890d57)

The next release will include this change and you will not need to use the `dev` version.
