### ISSUE TITLE
Add verification to ensure the Lustre filesystem can be client mounted

### ISSUE THREAD

**Issue by magicite** [NearNodeFlash/NearNodeFlash.github.io#12]
Ported from internal RABSW-670:
> After creation of the Lustre filesystem does the Rabbit perform any additional verification to ensure the filesystem was created as intended and can be mounted?

**Comment by magicite** [comment]
FYI @behlendorf

**Comment by matthew-richerson** [comment]
The Lustre file system is temporarily mounted during the Setup phase. If the mount fails, the Setup phase will not complete.
