### ISSUE TITLE
Rabbit must create namespaces at least big enough for zpool to create its metadata

### ISSUE THREAD

**Issue by ajfloeder** [NearNodeFlash/NearNodeFlash.github.io#131]
The absolute minimum device size we can allow turns out to be 142,606,336 bytes for a zpool. For a normally configured rabbit with 16 drives, that is:

```
142606336 * 16 = 2,281,701,376

To give some elbow room, the minimum allocation will be 4GB (256 MB * 16 drives).

**Comment by roehrich-hpe** [comment]
Can we point at a zfs doc or a zpool manpage where this info can be found?
