### ISSUE TITLE
Testing / kind environment: marking `Storage` compute nodes as offline

### ISSUE THREAD

**Issue by jameshcorbett** [NearNodeFlash/NearNodeFlash.github.io#146]
For testing purposes it would be nice if there was a mechanism to mark compute nodes as "Offline" in the Storage resource so that I could check that Flux handles the update correctly.

At the moment if I edit the resource it seems to be reverted immediately.

**Comment by roehrich-hpe** [comment]
PR https://github.com/DataWorkflowServices/dws/pull/192
