### ISSUE TITLE
Add new DW directive for enabling nnf-dm

### ISSUE THREAD

**Issue by bdevcich** [NearNodeFlash/NearNodeFlash.github.io#164]
Users need a way to specify that they want to do data movement while their application is running with the Copy Offload API and nnf-dm.

The directive breakdown can then be used to communicate back to flux that the nnf-dm needs to be started.

**Comment by matthew-richerson** [comment]
As a reminder, the DirectiveBreakdown resource is part of DWS (not Rabbit SW), so the new field shouldn't be Rabbit specific. Something like "RequiredDaemons=[nnf-dm]" rather than "NeedsNnfDM=true".

**Comment by roehrich-hpe** [comment]
Closed with https://github.com/NearNodeFlash/NearNodeFlash.github.io/pull/177
