### ISSUE TITLE
Race between `persistentdw` and `destroy_persistent`

### ISSUE THREAD

**Issue by bdevcich** [NearNodeFlash/NearNodeFlash.github.io#169]
With system-test where workflows are running in parallel (`J>1`), it can hit a case where the persistent usage tests are racing with the destroy case. What happens is that the workflow using the persistent storage can't finish `PreRun` because the destroy workflow beats it. Then both workflows are stuck until the usage workflow is removed.

So we end up with:

```shell
$ kubectl get workflows
NAME                         STATE      READY   STATUS       JOBID         AGE
fluxjob-172781307426766848   PreRun     false   DriverWait   fQGBxxiWiv3   30m
fluxjob-172781996030820352   Teardown   false   Error        fQGCH3r6VR9   29m
```

`NnfAccess`  for the usage workflow says:

```
status:
  error:
    debugMessage: 'unable to create ClientMount resources: ClientMount.dataworkflowservices.github.io
      "default-fluxjob-172781307426766848-0-computes" is invalid: spec.mounts: Invalid
      value: 0: spec.mounts in body should have at least 1 items'
    severity: Minor
    type: Internal
    userMessage: unable to mount file system on client nodes
```

There's no ClientMount yet.

The destroy workflow says: 

```
  message: 'DW Directive 0: User error: persistent storage cannot be deleted while
    in use'
  ready: false
  readyChange: "2024-06-20T20:09:44.290609Z"
  state: Teardown
  status: Error
```

Could the destroy proposal check the directivebreakdowns for any use of the directive name before it can leave Proposal? That way, as long as any usage workflow is out of proposal, there should be a directive breakdown that contains the persistent name:

```
  directive: '#DW persistentdw name=persistent-xfs-7c8c30f2'
```

Then the destroy can't get out of proposal until there are no directivebreakdowns left that contain that persistent name.

**Comment by bdevcich** [comment]
[fluxjob-172781307426766848.zip](https://github.com/user-attachments/files/15919967/fluxjob-172781307426766848.zip)
[fluxjob-172781996030820352.zip](https://github.com/user-attachments/files/15919968/fluxjob-172781996030820352.zip)

**Comment by bdevcich** [comment]
[fluxjob-172781307426766848.zip](https://github.com/user-attachments/files/15919979/fluxjob-172781307426766848.zip)
[fluxjob-172781996030820352.zip](https://github.com/user-attachments/files/15919980/fluxjob-172781996030820352.zip)

**Comment by matthew-richerson** [comment]
@bdevcich can this be closed?

**Comment by bdevcich** [comment]
> @bdevcich can this be closed?

Yes. Do you have the flux issue we can link?

**Comment by matthew-richerson** [comment]
Flux issue: https://github.com/flux-framework/flux-coral2/issues/170
