### ISSUE TITLE
ExternalMgs NID 0 suffix must be dropped

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/NearNodeFlash.github.io#175]
When specifying an `externalMGs` in the nnfstorageprofile yaml the LNET network ID must be dropped if it's zero.  Failure to do so will result in a workflow hung in Setup which cannot unmount the ephemeral Lustre filesystem.

Works: `51@kfi:32@kfi`
Fails: `51@kfi0:32@kfi0`

**Comment by matthew-richerson** [comment]
This has been fixed in the master branch (f87b6d8a249783460b9174e1e79ee6715b6763c5). It will be in the next release.
