### ISSUE TITLE
Mount rabbit-based MGTs on startup

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/NearNodeFlash.github.io#183]
When using a Lustre MGT backed by a persistentstorage instance it should be automatically mounted when the pods are started.  Otherwise, when a Rabbit nodes gets rebooted some number of MGTs won't be available resulting in failed workflows.

**Comment by matthew-richerson** [comment]
I put in a fix to make sure Lustre targets are remounted when the nnf-node-manager pod restarts.
https://github.com/NearNodeFlash/nnf-sos/commit/a2246392cd0a86b7b270efc3def4029b37a494cd
