### ISSUE TITLE
Skip down MGTs for Lustre workflows

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/NearNodeFlash.github.io#184]
When requesting a Lustre workflow with a storageprofile that uses the rabbit-backed pooled MGTs any offline MGTs should be skipped to avoid workflow failures on Setup.

**Comment by matthew-richerson** [comment]
This was fixed in nnf-sos: https://github.com/NearNodeFlash/nnf-sos/commit/6cb5f862b33b5879f0b21743aea32bc80e717e7a
