### ISSUE TITLE
Reflect down computes in 'storage' resource

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/NearNodeFlash.github.io#193]
The `status.access.computes[].status` field in the storage resource can report "Ready" even when the attached compute node is powered off.  I suspect powering off a compute after the rabbit node is up is sufficient to get in to this state.  Some mechanism is needed to keep the k8s resource status in sync with the actual hardware status.

**Comment by ajfloeder** [comment]
This issue stems for nnf-ec's stale view of the link status. How exactly that link status becomes stale is under investigation.

**Comment by ajfloeder** [comment]
For the time being, we'll poll the link status every minute to keep it up to date.
