### ISSUE TITLE
`SystemConfiguration` gets stuck on undeploy

### ISSUE THREAD

**Issue by bdevcich** [NearNodeFlash/NearNodeFlash.github.io#221]
When undeploying, the `SystemConfiguration` gets stuck and blocks the undeploy. It will hang at this point:

```
$ ./tools/undeploy-env.sh -e htx-1
application.argoproj.io "1-site-config" deleted
application.argoproj.io "1-global-lustre" deleted
application.argoproj.io "1-dws" deleted
application.argoproj.io "2-nnf-sos" deleted
application.argoproj.io "3-nnf-dm" deleted

```

It appears that DWS is not removing its finalizer from the SystemConfiguration when it gets deleted. To workaround, you must edit the `SystemConfiguration` and manually remove the DWS finalizer.

**Comment by roehrich-hpe** [comment]
Another idea:
Move `environments/htx-1/nnf-sos/systemconfiguration.yaml` into `environments/htx-1/site-config`. That should allow some delay between the removal of the SystemConfiguration and the removal of DWS.

**Comment by bdevcich** [comment]
> Another idea:
> Move `environments/htx-1/nnf-sos/systemconfiguration.yaml` into `environments/htx-1/site-config`. That should allow some delay between the removal of the SystemConfiguration and the removal of DWS.

This works on htx-1.
