### ISSUE TITLE
Feedback on RFC 2: Rabbit storage for containerized applications

### ISSUE THREAD

**Issue by NateThornton** [NearNodeFlash/NearNodeFlash.github.io#3]
Need approval from LLNL on the USER and ADMINISTRATOR roles as described in [RFC 0002: Rabbit Storage For Containerized Applications](https://github.com/NearNodeFlash/NearNodeFlash.github.io/blob/main/docs/rfcs/0002/readme.md).

**Comment by bdevcich-hpe** [comment]
Since a good chunk of the Containers RFC has been implemented, I'm inclined to close #28 and start converting it to documentation.

There are still some things to resolve, mainly #66 and #67.
