### ISSUE TITLE
Distinguishing fatal errors from transient errors

### ISSUE THREAD

**Issue by jameshcorbett** [NearNodeFlash/NearNodeFlash.github.io#46]
There needs to be a way for Flux to distinguish fatal errors from transient errors. When a fatal error occurs, Flux should be able to report back to the users immediately that their jobs hit a fatal error. Users will want to know the difference between "something took too long so we gave up" and "we hit a hard error, you [the user] may have done something wrong."

**Comment by matthew-richerson** [comment]
This change was included in nnf-deploy release v0.0.4
