### ISSUE TITLE
workflow jobID should be a string and show up in 'kubectl get workflows' output

### ISSUE THREAD

**Issue by ajfloeder** [NearNodeFlash/NearNodeFlash.github.io#65]
Flux's jobIDs are not numeric, so jobID or its replacement should accept a string.

Also, the jobID should be displayed as part of the `kubectl get workflows` default output.

**Comment by behlendorf** [comment]
I can see it being convenient to include the job ID in the default output rather than the "wide" version.

**Comment by roehrich-hpe** [comment]
Done:
https://github.com/HewlettPackard/dws/pull/138
https://github.com/NearNodeFlash/nnf-sos/pull/197
