### ISSUE TITLE
Let a set of rabbit nodes be used as the "external" MGS nodes.

### ISSUE THREAD

**Issue by roehrich-hpe** [NearNodeFlash/NearNodeFlash.github.io#83]
In discussion with @jameshcorbett  and @bdevcich-hpe  6/27/23:
James requested that he be able to setup a specified number of rabbits as MGS nodes, and then that Flux be able to pick from those MGS's when it's creating a new Lustre filesystem.
We suggested that he create a collection of persistentdw's to create the MGS's.  Then let Flux specify one of those MGS's via the Servers resource.  Then we'd substitute that into the pinned NnfStorageProfile as its externalMgs.

**Comment by roehrich-hpe** [comment]
Further request:
Add a keyword to the persistentdw DW line that marks it as belonging to this collection of MGS nodes, and put them in a list in some Rabbit resource so Flux can look there for the complete list, and Rabbit can maintain the list when it is asked to destroy a persistentdw.

**Comment by jameshcorbett** [comment]
This sounds very promising, thanks. I'll discuss with my team lead.

**Comment by matthew-richerson** [comment]
This change was included in nnf-deploy release v0.0.4
